version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20  # Versión requerida por vite-plugin-glsl
    commands:
      - npm ci
      
  build:
    commands:
      - export START_TIME=$(date +"%Y-%m-%d_%H-%M-%S") && npm exec vite build -- --mode production
      - ls -la dist  # Listamos el contenido de 'dist' para verificar que existan los archivos

artifacts:
  files:
    - '**/*'
  base-directory: dist
