version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Versión explícita de Node
    commands:
      - npm ci  # Instala TODAS las dependencias (incluyendo devDependencies)
      
  build:
    commands:
      - npm exec vite build -- --mode production  # Ejecuta vite desde node_modules
      # Alternativa:
      - ./node_modules/.bin/vite build --mode production

artifacts:
  files:
    - 'dist/**/*'
  base-directory: dist