version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20  # Versión requerida por vite-plugin-glsl
    commands:
      - npm ci
      
  build:
    commands:
      - npm exec vite build -- --mode production
      - ls -la
      

artifacts:
  files:
    - 'dist/**/*'
  base-directory: dist